function apply_stats_ranges_overlay(ax_handle, data_output, az, el)

    plot3(ax_handle,...
        data_output.positions.mean(1),data_output.positions.mean(2),...
        data_output.positions.mean(3),'xk','MarkerSize',10);
    
%     circle_plot(ax_handle, [0 0 0], data_output.distances.mean, az, el, 'k-');
    circle_plot(ax_handle, [0 0 0], data_output.distances.median, az, el, 'k-');
    circle_plot(ax_handle, [0 0 0], data_output.distances.first_quartile, az, el, 'k:');
    circle_plot(ax_handle, [0 0 0], data_output.distances.third_quartile, az, el, 'k:');
    circle_plot(ax_handle, [0 0 0], data_output.distances.residue_level_mean, az, el, 'r-');
    

%     rectangle(figure_handle.CurrentAxes, 'Position',[...
%         -data_output.distances.mean -data_output.distances.mean...
%         2*data_output.distances.mean 2*data_output.distances.mean],'Curvature',[1 1]);
%     
%     rectangle(figure_handle.CurrentAxes, 'Position',[...
%         -data_output.distances.median -data_output.distances.median...
%         2*data_output.distances.median 2*data_output.distances.median],'Curvature',[1 1],'LineStyle','--');
%     
%     rectangle(figure_handle.CurrentAxes, 'Position',[...
%         -data_output.distances.first_quartile -data_output.distances.first_quartile...
%         2*data_output.distances.first_quartile 2*data_output.distances.first_quartile],'Curvature',[1 1],'LineStyle',':');
%     
%     rectangle(figure_handle.CurrentAxes, 'Position',[...
%         -data_output.distances.third_quartile -data_output.distances.third_quartile...
%         2*data_output.distances.third_quartile 2*data_output.distances.third_quartile],'Curvature',[1 1],'LineStyle',':');
%     
%     rectangle(figure_handle.CurrentAxes, 'Position',[...
%         -data_output.distances.residue_level_mean -data_output.distances.residue_level_mean...
%         2*data_output.distances.residue_level_mean 2*data_output.distances.residue_level_mean],'Curvature',[1 1],'EdgeColor','r');
end
