function pdb_filepaths = Get_Talin_PDB_Filepaths()
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
pdb_filepaths = [ ...
    "pdb_data/R1.pdb",...
    "pdb_data/R2.pdb",...
    "pdb_data/R3.pdb",...
    "pdb_data/R4.pdb",...
    "pdb_data/R5.pdb",...
    "pdb_data/R6.pdb",...
    "pdb_data/R7R8.pdb",...
    "pdb_data/R7R8.pdb",...
    "pdb_data/R9.pdb",...
    "pdb_data/R10.pdb",...
    "pdb_data/R11.pdb",...
    "pdb_data/R12.pdb",...
    "pdb_data/R13.pdb",...
    ];
end

